= Publication identifiers library

Pubid is a comprehensive framework for building and working with publication identifiers. It provides a robust API for creating, modifying, parsing, exporting, and verifying document identifiers, which are crucial for various document management systems and standards compliance.

== Current use cases
Current use cases are what we needed until now and discovered through application to pubid-* and relaton-* projects. It's not complete and will be expanding during an integration process.

- build identifiers from scratch
- modifiying identifiers
- parsing string identifiers
- exporting/importing to different formats or styles (hash, yaml, URN, etc.)
- verification of compliance for identifier's representation standard (NIST PubID 1.0 for NIST, RFC 5141 for ISO URN) or using commonly discoveried patterns.
- verification of correctness for provided input.
- comparison two provided identifiers (with excluding attributes)
- converting legacy identifiers to updated format

== Vision

The pubid library should be utilized wherever operations on publication identifiers are required. It serves as an intermediary between users and publication identifiers, streamlining the creation, modification, comparison, and attribute access processes. By centralizing these operations in pubid-core, we ensure that any updates to identifier standards are seamlessly integrated across all related projects.

== Future
- Pubid algebra (extended comparison between different pubid)

== Usage

=== Exclude attributes when compare

[source,ruby]
----
require "pubid-core"

pubid_first = Identifier.parse("ISO 1:1999")
pubid_second = Identifier.parse("ISO 1")

pubid_first == pubid_second
=> false

pubid_first.exclude(:year) == pubid_second
=> true
----

=== Using #to_h to convert identifier to hash


[source,ruby]
----
require "pubid-core"

pubid = Identifier.parse("ISO 1:1999")
pubid.to_h
=> { publisher: "ISO", number: 1, year: 1999 }
----
